apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api
  labels:
    name: app-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app-api
  template:
    metadata:
      labels:
        name: app-api
    spec:
      containers:
      - name: app-api
        image: agustadewa/k
        ports:
        - name: node
          containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name:  app-api
  labels:
    name: app-api
  spec:
    type: NodePort
    ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
  selector:
    name: app-api