name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag yosiaagusta/k-img:latest
      
    - uses: actions/checkout@v2
    - name: Push Docker image
      run: docker push yosiaagusta/k-img:latest
  